vich_uploader:
    db_driver: orm

    mappings:
        oeuvre:
            uri_prefix: /images/oeuvres
            upload_destination: '%kernel.project_dir%/public/images/oeuvres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        year_directory_img:
            uri_prefix: /images/years_directory_img
            upload_destination: '%kernel.project_dir%/public/images/years_directory_img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        bio_img:
            uri_prefix: /images/bio_img
            upload_destination: '%kernel.project_dir%/public/images/bio_img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer